controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_register:
        path: /register
        controller: App\Controller\RegistrationController::register

app_login:
        path: /
        controller: App\Controller\SecurityController::login


    #[Route('/register', name: '')]

     #[Route(path: '/login', name: ')]
